language: python
jobs:
  include:
    - python: 3.6
      env: TARGET=release/linux_x86_64-cp-36-cp36m.zip
    - python: 3.7
      env: TARGET=release/linux_x86_64-cp-37-cp37m.zip
before_install:
  - apt install nodejs npm
install:
  - cd wechat-push-vue && npm install & cd ..
  - pip install -r server/requirements-dev.txt
script:
  - cd wechat-push-vue && npm run build & cd ..
  - cd server && python src/test.py & cd ..
  - NO_MIRROR=1 make $TARGET
