language: python
os:
  - linux
dist: bionic

jobs:
  include:
  - language: python
    python: 3.6
    before_install:
      - export _PY=$(python3 -c "v=__import__('sys').version_info;print('{}{}'.format(v.major,v.minor))")
      - sudo apt update
      - sudo apt-get install -y nodejs-dev node-gyp libssl1.0-dev
      - sudo apt-get install -y nodejs npm
    install:
      - cd wechat-push-vue && npm install && cd ..
      - pip install -r server/requirements-dev.txt
    script:
      - cd wechat-push-vue && npm run build && cd ..
      - cd server && python src/test.py && cd ..
      - NO_MIRROR=1 make release/wechat_push_linux_x86_64-cp-${_PY}-cp${_PY}m.zip

  - language: python
    python: 3.7
    before_install:
      - export _PY=$(python3 -c "v=__import__('sys').version_info;print('{}{}'.format(v.major,v.minor))")
      - sudo apt update
      - sudo apt-get install -y nodejs-dev node-gyp libssl1.0-dev
      - sudo apt-get install -y nodejs npm
    install:
      - cd wechat-push-vue && npm install && cd ..
      - pip install -r server/requirements-dev.txt
    script:
      - cd wechat-push-vue && npm run build && cd ..
      - cd server && python src/test.py && cd ..
      - NO_MIRROR=1 make release/wechat_push_linux_x86_64-cp-${_PY}-cp${_PY}m.zip
  
  - language: python
    python: 3.7
    services: docker
    install:
      - export TAG=$(git describe --tags)
      - docker-compose build
