language: python
python:
  - 3.6
  - 3.7
os:
  - linux
dist: bionic
before_install:
  - apt install nodejs npm
install:
  - cd wechat-push-vue && npm install & cd ..
  - pip install -r server/requirements-dev.txt
script:
  - cd wechat-push-vue && npm run build & cd ..
  - cd server && python src/test.py & cd ..
  - NO_MIRROR=1 make $TRAVIS_OS_NAME
