matrix:
  include:
    - 
      language: python
      python: "3.6"
      install:
        - pip install -r server/requirements-dev.txt
      before_script:
        - cd server
      script:
        - python src/test.py
        - NO_MIRROR=1 make build/wechat_push_linux_x86_64-cp-36-cp36m.pex
    - 
      language: python
      python: "3.7"
      install:
        - pip install -r server/requirements-dev.txt
      before_script:
        - cd server
      script:
        - python src/test.py
        - NO_MIRROR=1 make build/wechat_push_linux_x86_64-cp-37-cp37m.pex
    - 
      language: node_js
      node_js: "9"
      before_install:
        - cd detail-page
      install:
        - npm install
      script:
        - npm run build
    - 
      language: node_js
      node_js: "10"
      before_install:
        - cd detail-page
      install:
        - npm install
      script:
        - npm run build