matrix:
  include:
    - 
      language: python
      python:
        - "3.6"
        - "3.7"
      install:
        - pip install -r server/requirements-dev.txt
      before_script:
        - cd server
      script:
        - python src/test.py
        - make
    - 
      language: node_js
      node_js:
        - "9"
        - "10"
      before_install:
        - cd detail-page
      install:
        - npm install
      before_script:
        - cd detail-page
      script:
        - npm run build
      